### ISSUE TITLE
Scanning Large Networks

### ISSUE THREAD

**Issue by trvon** [trvon/SpaceSecure#5]
I've noticed when trying to scan networks with over 8000 devices, the program cycles for a while when processing the file from the scan, whereas the scan only takes 30 seconds. There is also an interesting glitch where it doesn't even transfer the contents of the scan to the connected Devices file.

**Comment by rahulr56** [comment]
Updated the regular expression. arp-scan has some internal issue while scanning larger networks. So, displayed an error message as well.

**Comment by rahulr56** [comment]
@trvon , There will be an error message "ERROR: failed to send packet: Resource temporarily unavailable" from arp-scan in that case, only a few devices that are scanned will be shown in the list. Could you verify this functionality again in the large network?

I will close this issue once you come back with your results

**Comment by trvon** [comment]
I am seeing connectedDevices.txt not displaying any items after running the script. I tried running the script by its self and using cat to view the contents but it still shows up as blank.

**Comment by rahulr56** [comment]
Have you tried it out now?

**Comment by trvon** [comment]
I tried it a couple minutes ago after pulling. The temp file had all the connectedDevices, but the connectedDevices.txt was still blank even after the grep use.

**Comment by rahulr56** [comment]
Try it out now! I have updated the script!

**Comment by trvon** [comment]
The scan isn't working again. It must have used an existing connectedDevices.txt when I ran it but now no file is spawning when I scan. I Think the back end isn't calling the script properly.

**Comment by trvon** [comment]
I am seeing there is a problem between running the build scripts and running the GUI from its folder. The GUI is able to call the backend scan but can't reach the connectedDevices file whereas the build scripts isn't able to call scan function in the GUI.
