### ISSUE TITLE
Resize the GUI

### ISSUE THREAD

**Issue by rahulr56** [trvon/SpaceSecure#6]
Resizing the window is showing me weird pattern. If the window is shrunk to as small as possible and is expanded again, the options and the contents of the actual window are not shown again!

**Comment by trvon** [comment]
I'll start working on that now. I fixed the resizing of the GUI so certain fields are locked, but I haven't fully mastered setting a max and min resize for the GUI.

**Comment by trvon** [comment]
Let me know if you are still having a problem with resizing the GUI.
